version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka-1:
    image: wurstmeister/kafka
    container_name: kafka-1
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka-1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - 9092
    depends_on:
      - zookeeper

  kafka-2:
    image: wurstmeister/kafka
    container_name: kafka-2
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka-2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - 9092
    depends_on:
      - zookeeper

  kafka-3:
    image: wurstmeister/kafka
    container_name: kafka-3
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka-3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - 9092
    depends_on:
      - zookeeper